//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilverlightVisualDesigners.EditControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditShowDataFormControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public EditShowDataFormControl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilverlightVisualDesigners.EditControls.EditShowDataFormControl", typeof(EditShowDataFormControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string button_Cancel {
            get {
                return ResourceManager.GetString("button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string button_Ok {
            get {
                return ResourceManager.GetString("button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string check_Bold {
            get {
                return ResourceManager.GetString("check_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string check_Italic {
            get {
                return ResourceManager.GetString("check_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available fields.
        /// </summary>
        public static string textBlock_AvailableFields {
            get {
                return ResourceManager.GetString("textBlock_AvailableFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed fields.
        /// </summary>
        public static string textBlock_DisplayedFields {
            get {
                return ResourceManager.GetString("textBlock_DisplayedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        public static string textBlock_FontColor {
            get {
                return ResourceManager.GetString("textBlock_FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Name.
        /// </summary>
        public static string textBlock_FontName {
            get {
                return ResourceManager.GetString("textBlock_FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string textBlock_FontSize {
            get {
                return ResourceManager.GetString("textBlock_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Format.
        /// </summary>
        public static string textBlock_TextFormat {
            get {
                return ResourceManager.GetString("textBlock_TextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Data Form Configuration.
        /// </summary>
        public static string textBlock_TilteBar {
            get {
                return ResourceManager.GetString("textBlock_TilteBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Title.
        /// </summary>
        public static string textBock_FormTitle {
            get {
                return ResourceManager.GetString("textBock_FormTitle", resourceCulture);
            }
        }
    }
}
