//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtnEmall.ServerManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UtnEmall.ServerManager.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add campaign.
        /// </summary>
        public static string AddCampaign {
            get {
                return ResourceManager.GetString("AddCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add categories.
        /// </summary>
        public static string AddCategories {
            get {
                return ResourceManager.GetString("AddCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add category.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add customer.
        /// </summary>
        public static string AddCustomer {
            get {
                return ResourceManager.GetString("AddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add data model.
        /// </summary>
        public static string AddDataModel {
            get {
                return ResourceManager.GetString("AddDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group.
        /// </summary>
        public static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add permission.
        /// </summary>
        public static string AddPermission {
            get {
                return ResourceManager.GetString("AddPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add service.
        /// </summary>
        public static string AddService {
            get {
                return ResourceManager.GetString("AddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add store.
        /// </summary>
        public static string AddStore {
            get {
                return ResourceManager.GetString("AddStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available categories.
        /// </summary>
        public static string AvailableCategories {
            get {
                return ResourceManager.GetString("AvailableCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available fields.
        /// </summary>
        public static string AvailableFields {
            get {
                return ResourceManager.GetString("AvailableFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Service.....
        /// </summary>
        public static string BuildingService {
            get {
                return ResourceManager.GetString("BuildingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category selector.
        /// </summary>
        public static string CategorySelector {
            get {
                return ResourceManager.GetString("CategorySelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil State.
        /// </summary>
        public static string CivilState {
            get {
                return ResourceManager.GetString("CivilState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicks.
        /// </summary>
        public static string Clicks {
            get {
                return ResourceManager.GetString("Clicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Modality.
        /// </summary>
        public static string DataModality {
            get {
                return ResourceManager.GetString("DataModality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Model Designer.
        /// </summary>
        public static string DataModelDesigner {
            get {
                return ResourceManager.GetString("DataModelDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display data properties.
        /// </summary>
        public static string DisplayDataProperties {
            get {
                return ResourceManager.GetString("DisplayDataProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed fields.
        /// </summary>
        public static string DisplayedFields {
            get {
                return ResourceManager.GetString("DisplayedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Dialog.
        /// </summary>
        public static string ErrorDialog {
            get {
                return ResourceManager.GetString("ErrorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Statistics.
        /// </summary>
        public static string GlobalStatistics {
            get {
                return ResourceManager.GetString("GlobalStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Statistics Analyzer.
        /// </summary>
        public static string GlobalStatisticsAnalyzer {
            get {
                return ResourceManager.GetString("GlobalStatisticsAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of children.
        /// </summary>
        public static string HowManyChildren {
            get {
                return ResourceManager.GetString("HowManyChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal phone.
        /// </summary>
        public static string InternalPhone {
            get {
                return ResourceManager.GetString("InternalPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List output.
        /// </summary>
        public static string ListOutput {
            get {
                return ResourceManager.GetString("ListOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Properties.
        /// </summary>
        public static string ListProperties {
            get {
                return ResourceManager.GetString("ListProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in, select one of the items on the menu to start..
        /// </summary>
        public static string LoggedInMessage {
            get {
                return ResourceManager.GetString("LoggedInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage categories.
        /// </summary>
        public static string ManageCampaigns {
            get {
                return ResourceManager.GetString("ManageCampaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage categories.
        /// </summary>
        public static string ManageCategories {
            get {
                return ResourceManager.GetString("ManageCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage customers.
        /// </summary>
        public static string ManageCustomers {
            get {
                return ResourceManager.GetString("ManageCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage data model.
        /// </summary>
        public static string ManageDataModel {
            get {
                return ResourceManager.GetString("ManageDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage groups.
        /// </summary>
        public static string ManageGroups {
            get {
                return ResourceManager.GetString("ManageGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage permissions.
        /// </summary>
        public static string ManagePermissions {
            get {
                return ResourceManager.GetString("ManagePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage services.
        /// </summary>
        public static string ManageServices {
            get {
                return ResourceManager.GetString("ManageServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage stores.
        /// </summary>
        public static string ManageStores {
            get {
                return ResourceManager.GetString("ManageStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many to many.
        /// </summary>
        public static string ManyToMany {
            get {
                return ResourceManager.GetString("ManyToMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu options.
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu properties.
        /// </summary>
        public static string MenuProperties {
            get {
                return ResourceManager.GetString("MenuProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New table.
        /// </summary>
        public static string NewTable {
            get {
                return ResourceManager.GetString("NewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One to many.
        /// </summary>
        public static string OneToMany {
            get {
                return ResourceManager.GetString("OneToMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One to one.
        /// </summary>
        public static string OneToOne {
            get {
                return ResourceManager.GetString("OneToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relations.
        /// </summary>
        public static string Relations {
            get {
                return ResourceManager.GetString("Relations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all.
        /// </summary>
        public static string RemoveAll {
            get {
                return ResourceManager.GetString("RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove category.
        /// </summary>
        public static string RemoveCategory {
            get {
                return ResourceManager.GetString("RemoveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected categories.
        /// </summary>
        public static string SelectedCategories {
            get {
                return ResourceManager.GetString("SelectedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;Global statistics&quot; if you want to see resumed information of the usage of all the services.
        /// </summary>
        public static string SelectGlobalStatisticsMessage {
            get {
                return ResourceManager.GetString("SelectGlobalStatisticsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a service and then click &quot;View&quot; if you want to see statistics of a specific service..
        /// </summary>
        public static string SelectServiceStatisticsMessage {
            get {
                return ResourceManager.GetString("SelectServiceStatisticsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Manager.
        /// </summary>
        public static string ServerManagerTitle {
            get {
                return ResourceManager.GetString("ServerManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Designer.
        /// </summary>
        public static string ServiceDesigner {
            get {
                return ResourceManager.GetString("ServiceDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start form:.
        /// </summary>
        public static string SetStartForm {
            get {
                return ResourceManager.GetString("SetStartForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Data.
        /// </summary>
        public static string ShowData {
            get {
                return ResourceManager.GetString("ShowData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Detail.
        /// </summary>
        public static string ShowDetail {
            get {
                return ResourceManager.GetString("ShowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show preferences.
        /// </summary>
        public static string ShowPreferences {
            get {
                return ResourceManager.GetString("ShowPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop date.
        /// </summary>
        public static string StopDate {
            get {
                return ResourceManager.GetString("StopDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store number.
        /// </summary>
        public static string StoreNumber {
            get {
                return ResourceManager.GetString("StoreNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table properties.
        /// </summary>
        public static string TableProperties {
            get {
                return ResourceManager.GetString("TableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text input properties.
        /// </summary>
        public static string TextInputProperties {
            get {
                return ResourceManager.GetString("TextInputProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.0.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Statistics.
        /// </summary>
        public static string ViewStatistics {
            get {
                return ResourceManager.GetString("ViewStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to UtnEmall Server Manager Project. In this window you will be able to manage all the tasks related to UtnEmall Server..
        /// </summary>
        public static string WelcomeTextBlock {
            get {
                return ResourceManager.GetString("WelcomeTextBlock", resourceCulture);
            }
        }
    }
}
