//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PresentationLayer.GeneralResources", typeof(GeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application.
        /// </summary>
        public static string ApplicationHelp {
            get {
                return ResourceManager.GetString("ApplicationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process failed because of a connection problem..
        /// </summary>
        public static string CommunicationException {
            get {
                return ResourceManager.GetString("CommunicationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configuration.
        /// </summary>
        public static string ConfigurationHelp {
            get {
                return ResourceManager.GetString("ConfigurationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Installation.
        /// </summary>
        public static string ConfirmServiceInstallationTitle {
            get {
                return ResourceManager.GetString("ConfirmServiceInstallationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the service?.
        /// </summary>
        public static string ConfirmServiceUninstall {
            get {
                return ResourceManager.GetString("ConfirmServiceUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in.
        /// </summary>
        public static string ConnectionStateSuccess {
            get {
                return ResourceManager.GetString("ConnectionStateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer can&apos;t be null..
        /// </summary>
        public static string CustomerNullArgument {
            get {
                return ResourceManager.GetString("CustomerNullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device information was not found..
        /// </summary>
        public static string DeviceInfoNotFoundError {
            get {
                return ResourceManager.GetString("DeviceInfoNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device info not found..
        /// </summary>
        public static string DeviceNotFoundError {
            get {
                return ResourceManager.GetString("DeviceNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac address is empty..
        /// </summary>
        public static string DeviceProfileFormMACError {
            get {
                return ResourceManager.GetString("DeviceProfileFormMACError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device model is empty..
        /// </summary>
        public static string DeviceProfileFormModelError {
            get {
                return ResourceManager.GetString("DeviceProfileFormModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device type is empty..
        /// </summary>
        public static string DeviceProfileFormTypeError {
            get {
                return ResourceManager.GetString("DeviceProfileFormTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows mobile version is empty..
        /// </summary>
        public static string DeviceProfileFormVersionError {
            get {
                return ResourceManager.GetString("DeviceProfileFormVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t complete the operation..
        /// </summary>
        public static string FileIOError {
            get {
                return ResourceManager.GetString("FileIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fileName can&apos;t be null..
        /// </summary>
        public static string FileNameNullArgument {
            get {
                return ResourceManager.GetString("FileNameNullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help can&apos;t be null or empty..
        /// </summary>
        public static string HelpNullArgument {
            get {
                return ResourceManager.GetString("HelpNullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any image to show..
        /// </summary>
        public static string ImageNotFoundError {
            get {
                return ResourceManager.GetString("ImageNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid host address.
        /// </summary>
        public static string InvalidHostAddressError {
            get {
                return ResourceManager.GetString("InvalidHostAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpServer can&apos;t be null..
        /// </summary>
        public static string IpNullArgument {
            get {
                return ResourceManager.GetString("IpNullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed, the password is incorrect..
        /// </summary>
        public static string LoginFailedPasswordIncorrect {
            get {
                return ResourceManager.GetString("LoginFailedPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed, the user name is incorrect..
        /// </summary>
        public static string LoginFailedUserIncorrect {
            get {
                return ResourceManager.GetString("LoginFailedUserIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to login..
        /// </summary>
        public static string LoginPermissionError {
            get {
                return ResourceManager.GetString("LoginPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string OfflineMessage {
            get {
                return ResourceManager.GetString("OfflineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string OnlineMessage {
            get {
                return ResourceManager.GetString("OnlineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping time can&apos;t be null..
        /// </summary>
        public static string PingNullArgument {
            get {
                return ResourceManager.GetString("PingNullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port server can&apos;t be null..
        /// </summary>
        public static string PortNullArgument {
            get {
                return ResourceManager.GetString("PortNullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is empty..
        /// </summary>
        public static string ProfileFormAddressError {
            get {
                return ResourceManager.GetString("ProfileFormAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is empty..
        /// </summary>
        public static string ProfileFormFirstNameError {
            get {
                return ResourceManager.GetString("ProfileFormFirstNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is empty..
        /// </summary>
        public static string ProfileFormPhoneError {
            get {
                return ResourceManager.GetString("ProfileFormPhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname is empty..
        /// </summary>
        public static string ProfileFormSurnameError {
            get {
                return ResourceManager.GetString("ProfileFormSurnameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer saved successfully..
        /// </summary>
        public static string SaveCustomerSuccess {
            get {
                return ResourceManager.GetString("SaveCustomerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mall configuration saved successfully..
        /// </summary>
        public static string SaveMallSuccess {
            get {
                return ResourceManager.GetString("SaveMallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serverNotFound.
        /// </summary>
        public static string ServerNotFoundHelp {
            get {
                return ResourceManager.GetString("ServerNotFoundHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to services.
        /// </summary>
        public static string ServiceHelp {
            get {
                return ResourceManager.GetString("ServiceHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while installing the service..
        /// </summary>
        public static string ServiceInstallationError {
            get {
                return ResourceManager.GetString("ServiceInstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Service?.
        /// </summary>
        public static string ServiceInstallationSuccess {
            get {
                return ResourceManager.GetString("ServiceInstallationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service removed.
        /// </summary>
        public static string ServiceRemoved {
            get {
                return ResourceManager.GetString("ServiceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t remove service. Please try again later..
        /// </summary>
        public static string ServiceRemoveError {
            get {
                return ResourceManager.GetString("ServiceRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Service.
        /// </summary>
        public static string ServiceUninstallTitle {
            get {
                return ResourceManager.GetString("ServiceUninstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process failed because of a connection problem..
        /// </summary>
        public static string TargetInvocationExceptionMessage {
            get {
                return ResourceManager.GetString("TargetInvocationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name and password can&apos;t be empty..
        /// </summary>
        public static string UserNameEmpty {
            get {
                return ResourceManager.GetString("UserNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UtnEmall Project.
        /// </summary>
        public static string UtnEmallProject {
            get {
                return ResourceManager.GetString("UtnEmallProject", resourceCulture);
            }
        }
    }
}
