//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtnEmall.ServerManager.SAL.CustomerServiceData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SAL.CustomerServiceData.ICustomerServiceData")]
    public interface ICustomerServiceData {

        [UtnEmall.Server.Core.ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServiceData/Save", ReplyAction="http://tempuri.org/ICustomerServiceData/SaveResponse")]
        UtnEmall.Server.EntityModel.CustomerServiceDataEntity Save(UtnEmall.Server.EntityModel.CustomerServiceDataEntity customerServiceDataEntity, string session);

        [UtnEmall.Server.Core.ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICustomerServiceData/Delete", ReplyAction = "http://tempuri.org/ICustomerServiceData/DeleteResponse")]
        UtnEmall.Server.EntityModel.CustomerServiceDataEntity Delete(UtnEmall.Server.EntityModel.CustomerServiceDataEntity customerServiceDataEntity, string session);

        [UtnEmall.Server.Core.ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICustomerServiceData/GetCustomerServiceData", ReplyAction = "http://tempuri.org/ICustomerServiceData/GetCustomerServiceDataResponse")]
        UtnEmall.Server.EntityModel.CustomerServiceDataEntity GetCustomerServiceData(int id, bool loadRelation, string session);

        [UtnEmall.Server.Core.ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICustomerServiceData/GetAllCustomerServiceData", ReplyAction = "http://tempuri.org/ICustomerServiceData/GetAllCustomerServiceDataResponse")]
        System.Collections.Generic.List<UtnEmall.Server.EntityModel.CustomerServiceDataEntity> GetAllCustomerServiceData(bool loadRelation, string session);

        [UtnEmall.Server.Core.ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICustomerServiceData/GetCustomerServiceDataWhere", ReplyAction = "http://tempuri.org/ICustomerServiceData/GetCustomerServiceDataWhereResponse")]
        System.Collections.Generic.List<UtnEmall.Server.EntityModel.CustomerServiceDataEntity> GetCustomerServiceDataWhere(string propertyName, object expValue, bool loadRelation, UtnEmall.Server.Base.OperatorType operatorType, string session);

        [UtnEmall.Server.Core.ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICustomerServiceData/GetCustomerServiceDataWhereEqual", ReplyAction = "http://tempuri.org/ICustomerServiceData/GetCustomerServiceDataWhereEqualResponse")]
        System.Collections.Generic.List<UtnEmall.Server.EntityModel.CustomerServiceDataEntity> GetCustomerServiceDataWhereEqual(string propertyName, object expValue, bool loadRelation, string session);

        [UtnEmall.Server.Core.ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICustomerServiceData/Validate", ReplyAction = "http://tempuri.org/ICustomerServiceData/ValidateResponse")]
        bool Validate(UtnEmall.Server.EntityModel.CustomerServiceDataEntity customerServiceData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICustomerServiceDataChannel : ServerManager.SAL.CustomerServiceData.ICustomerServiceData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CustomerServiceDataClient : System.ServiceModel.ClientBase<ServerManager.SAL.CustomerServiceData.ICustomerServiceData>, ServerManager.SAL.CustomerServiceData.ICustomerServiceData {
        
        public CustomerServiceDataClient() {
        }
        
        public CustomerServiceDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UtnEmall.Server.EntityModel.CustomerServiceDataEntity Save(UtnEmall.Server.EntityModel.CustomerServiceDataEntity customerServiceDataEntity, string session) {
            return base.Channel.Save(customerServiceDataEntity, session);
        }
        
        public UtnEmall.Server.EntityModel.CustomerServiceDataEntity Delete(UtnEmall.Server.EntityModel.CustomerServiceDataEntity customerServiceDataEntity, string session) {
            return base.Channel.Delete(customerServiceDataEntity, session);
        }
        
        public UtnEmall.Server.EntityModel.CustomerServiceDataEntity GetCustomerServiceData(int id, bool loadRelation, string session) {
            return base.Channel.GetCustomerServiceData(id, loadRelation, session);
        }
        
        public System.Collections.Generic.List<UtnEmall.Server.EntityModel.CustomerServiceDataEntity> GetAllCustomerServiceData(bool loadRelation, string session) {
            return base.Channel.GetAllCustomerServiceData(loadRelation, session);
        }

        public System.Collections.Generic.List<UtnEmall.Server.EntityModel.CustomerServiceDataEntity> GetCustomerServiceDataWhere(string propertyName, object expValue, bool loadRelation, UtnEmall.Server.Base.OperatorType operatorType, string session)
        {
            return base.Channel.GetCustomerServiceDataWhere(propertyName, expValue, loadRelation, operatorType, session);
        }
        
        public System.Collections.Generic.List<UtnEmall.Server.EntityModel.CustomerServiceDataEntity> GetCustomerServiceDataWhereEqual(string propertyName, object expValue, bool loadRelation, string session) {
            return base.Channel.GetCustomerServiceDataWhereEqual(propertyName, expValue, loadRelation, session);
        }
        
        public bool Validate(UtnEmall.Server.EntityModel.CustomerServiceDataEntity customerServiceData) {
            return base.Channel.Validate(customerServiceData);
        }
    }
}
