//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtnEmall.Server.WpfCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTN Emall Server - 2008 
        ///Universidad Tecnológica Nacional - Facultad Regional Córdoba
        ///
        ///Sample database image copyrights:
        ///Image 1:
        ///http://commons.wikimedia.org/wiki/File:Casa_de_Estudillo_-_bedroom.jpg
        ///Author: macmaroon from Canada
        ///License: Creative Commons Attribution 2.0
        ///Image 2:
        ///http://commons.wikimedia.org/wiki/File:EleanorRooseveltNationalHistoricSite_Bedroom_2007_02.jpg
        ///Author: Rolf Müller
        ///License: GDFL (GNU Free Documentation License)
        ///Image 3:
        ///http://commons.wikimedia.org/wiki/File:Restau [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTN-Emall Server.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has been minimized. You can double-click the tray icon to restore the window..
        /// </summary>
        public static string BalloonTipTextMinimized {
            get {
                return ResourceManager.GetString("BalloonTipTextMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is running..
        /// </summary>
        public static string BalloonTipTextStart {
            get {
                return ResourceManager.GetString("BalloonTipTextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTN-Emall Server.
        /// </summary>
        public static string BalloonTipTitle {
            get {
                return ResourceManager.GetString("BalloonTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fields can not be empty..
        /// </summary>
        public static string ConfigurationFields {
            get {
                return ResourceManager.GetString("ConfigurationFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database doesn&apos;t exist or the server name is incorrect..
        /// </summary>
        public static string ConfigurationMessage {
            get {
                return ResourceManager.GetString("ConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string ConfigurationTitle {
            get {
                return ResourceManager.GetString("ConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Custom Service is already deployed. Delete the current instance first..
        /// </summary>
        public static string CustomerServiceAlreadyDeployed {
            get {
                return ResourceManager.GetString("CustomerServiceAlreadyDeployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  does not exists. Do you want to build it?.
        /// </summary>
        public static string CustomServiceBuild {
            get {
                return ResourceManager.GetString("CustomServiceBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Service file: .
        /// </summary>
        public static string CustomServiceFile {
            get {
                return ResourceManager.GetString("CustomServiceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Custom Service.
        /// </summary>
        public static string CustomServiceTitle {
            get {
                return ResourceManager.GetString("CustomServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database host name.
        /// </summary>
        public static string DatabaseHostName {
            get {
                return ResourceManager.GetString("DatabaseHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data model is already deployed. Delete the current instance first..
        /// </summary>
        public static string DataModelAlreadyDeployed {
            get {
                return ResourceManager.GetString("DataModelAlreadyDeployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Customer Service&apos;s related data model must be deployed..
        /// </summary>
        public static string DataModelMustBeDeployed {
            get {
                return ResourceManager.GetString("DataModelMustBeDeployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data model must contain at least one table..
        /// </summary>
        public static string DataModelMustHaveOneTable {
            get {
                return ResourceManager.GetString("DataModelMustHaveOneTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string DebugTitle {
            get {
                return ResourceManager.GetString("DebugTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close UTN-Emall Server?.
        /// </summary>
        public static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitTitle {
            get {
                return ResourceManager.GetString("ExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while loading the service assembly. Details:.
        /// </summary>
        public static string FailureLoadingServiceAssemblyOrOtherError {
            get {
                return ResourceManager.GetString("FailureLoadingServiceAssemblyOrOtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while running a test on the Infrastructure Service..
        /// </summary>
        public static string FailureRunningTestOnInfrastructureService {
            get {
                return ResourceManager.GetString("FailureRunningTestOnInfrastructureService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A security error has occurred while loading the Infrastructure Service. Details :.
        /// </summary>
        public static string FailureSecurityErrorLoadingInfrastructureService {
            get {
                return ResourceManager.GetString("FailureSecurityErrorLoadingInfrastructureService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application failed to publish the infrastructure service..
        /// </summary>
        public static string FailureTryingToPublishInfrastructureService {
            get {
                return ResourceManager.GetString("FailureTryingToPublishInfrastructureService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error has occurred..
        /// </summary>
        public static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InformationTitle {
            get {
                return ResourceManager.GetString("InformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  does not exists. Do you want to build it?.
        /// </summary>
        public static string InfrastructureServiceBuild {
            get {
                return ResourceManager.GetString("InfrastructureServiceBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure file: .
        /// </summary>
        public static string InfrastructureServiceFile {
            get {
                return ResourceManager.GetString("InfrastructureServiceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Infrastructure Service.
        /// </summary>
        public static string InfrastructureServiceTitle {
            get {
                return ResourceManager.GetString("InfrastructureServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert the database host name..
        /// </summary>
        public static string InsertDatabaseHostName {
            get {
                return ResourceManager.GetString("InsertDatabaseHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ItemAbout {
            get {
                return ResourceManager.GetString("ItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ItemExit {
            get {
                return ResourceManager.GetString("ItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ItemOpen {
            get {
                return ResourceManager.GetString("ItemOpen", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Administration.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to attach the example database?.
        /// </summary>
        public static string MessageInstallDataBase {
            get {
                return ResourceManager.GetString("MessageInstallDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while saving the configuration..
        /// </summary>
        public static string MessageSaveFail {
            get {
                return ResourceManager.GetString("MessageSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server configuration was saved. Please restart the server..
        /// </summary>
        public static string MessageSaveSuccessful {
            get {
                return ResourceManager.GetString("MessageSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services on this database will be compiled. This will take a couple o minutes..
        /// </summary>
        public static string RecompilationOfServices {
            get {
                return ResourceManager.GetString("RecompilationOfServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon server {
            get {
                object obj = ResourceManager.GetObject("server", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Version.
        /// </summary>
        public static string ServerVersion {
            get {
                return ResourceManager.GetString("ServerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Server.
        /// </summary>
        public static string StopServer {
            get {
                return ResourceManager.GetString("StopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The infrastructure service was published successfully..
        /// </summary>
        public static string SuccessInfrastructureServicePublished {
            get {
                return ResourceManager.GetString("SuccessInfrastructureServicePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTN-Emall Server.
        /// </summary>
        public static string TrayText {
            get {
                return ResourceManager.GetString("TrayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file specifies the source and catalog for the connection string..
        /// </summary>
        public static string XMLDataAccessComment {
            get {
                return ResourceManager.GetString("XMLDataAccessComment", resourceCulture);
            }
        }
    }
}
