//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UtnEmall.Server.Core;
namespace WebApplication.ServiceReferenceStatisticsAnalyzer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceStatisticsAnalyzer.IStatisticsAnalyzer")]
    public interface IStatisticsAnalyzer {

        [ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsAnalyzer/GetRegistersClickAmount", ReplyAction="http://tempuri.org/IStatisticsAnalyzer/GetRegistersClickAmountResponse")]
        System.Collections.Generic.List<System.Collections.DictionaryEntry> GetRegistersClickAmount(UtnEmall.Server.EntityModel.ComponentEntity listFormComponent, string session);

        [ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsAnalyzer/GetRegisterClickPercentageAmount", ReplyAction="http://tempuri.org/IStatisticsAnalyzer/GetRegisterClickPercentageAmountResponse")]
        System.Collections.Generic.List<System.Collections.DictionaryEntry> GetRegisterClickPercentageAmount(UtnEmall.Server.EntityModel.ComponentEntity listFormComponent, string session);

        [ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsAnalyzer/GetCustomersAccessAmount", ReplyAction="http://tempuri.org/IStatisticsAnalyzer/GetCustomersAccessAmountResponse")]
        System.Collections.Generic.List<System.Collections.DictionaryEntry> GetCustomersAccessAmount(string session);

        [ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsAnalyzer/GetCustomersTimeAmountByStore", ReplyAction="http://tempuri.org/IStatisticsAnalyzer/GetCustomersTimeAmountByStoreResponse")]
        System.Collections.Generic.List<System.Collections.DictionaryEntry> GetCustomersTimeAmountByStore(UtnEmall.Server.EntityModel.StoreEntity store, string session);

        [ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsAnalyzer/GetCustomersAccessAmountByStore", ReplyAction="http://tempuri.org/IStatisticsAnalyzer/GetCustomersAccessAmountByStoreResponse")]
        System.Collections.Generic.List<System.Collections.DictionaryEntry> GetCustomersAccessAmountByStore(UtnEmall.Server.EntityModel.StoreEntity store, string session);

        [ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsAnalyzer/GetCustomersTimeAmount", ReplyAction="http://tempuri.org/IStatisticsAnalyzer/GetCustomersTimeAmountResponse")]
        System.Collections.Generic.List<System.Collections.DictionaryEntry> GetCustomersTimeAmount(string session);

        [ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsAnalyzer/GetCustomerFormAccessAmount", ReplyAction="http://tempuri.org/IStatisticsAnalyzer/GetCustomerFormAccessAmountResponse")]
        int GetCustomerFormAccessAmount(UtnEmall.Server.EntityModel.ComponentEntity component, string session);

        [ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsAnalyzer/GetFormAccessAmount", ReplyAction="http://tempuri.org/IStatisticsAnalyzer/GetFormAccessAmountResponse")]
        int GetFormAccessAmount(UtnEmall.Server.EntityModel.ComponentEntity component, string session);

        [ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsAnalyzer/GetMenuItemAccessAmounts", ReplyAction="http://tempuri.org/IStatisticsAnalyzer/GetMenuItemAccessAmountsResponse")]
        System.Collections.Generic.List<System.Collections.DictionaryEntry> GetMenuItemAccessAmounts(UtnEmall.Server.EntityModel.ComponentEntity component, string session);

        [ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsAnalyzer/GetMenuItemAccessAmount", ReplyAction="http://tempuri.org/IStatisticsAnalyzer/GetMenuItemAccessAmountResponse")]
        int GetMenuItemAccessAmount(UtnEmall.Server.EntityModel.ComponentEntity component, string session);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IStatisticsAnalyzerChannel : WebApplication.ServiceReferenceStatisticsAnalyzer.IStatisticsAnalyzer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class StatisticsAnalyzerClient : System.ServiceModel.ClientBase<WebApplication.ServiceReferenceStatisticsAnalyzer.IStatisticsAnalyzer>, WebApplication.ServiceReferenceStatisticsAnalyzer.IStatisticsAnalyzer {
        
        public StatisticsAnalyzerClient() {
        }
        
        public StatisticsAnalyzerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatisticsAnalyzerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticsAnalyzerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticsAnalyzerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<System.Collections.DictionaryEntry> GetRegistersClickAmount(UtnEmall.Server.EntityModel.ComponentEntity listFormComponent, string session) {
            return base.Channel.GetRegistersClickAmount(listFormComponent, session);
        }
        
        public System.Collections.Generic.List<System.Collections.DictionaryEntry> GetRegisterClickPercentageAmount(UtnEmall.Server.EntityModel.ComponentEntity listFormComponent, string session) {
            return base.Channel.GetRegisterClickPercentageAmount(listFormComponent, session);
        }
        
        public System.Collections.Generic.List<System.Collections.DictionaryEntry> GetCustomersAccessAmount(string session) {
            return base.Channel.GetCustomersAccessAmount(session);
        }
        
        public System.Collections.Generic.List<System.Collections.DictionaryEntry> GetCustomersTimeAmountByStore(UtnEmall.Server.EntityModel.StoreEntity store, string session) {
            return base.Channel.GetCustomersTimeAmountByStore(store, session);
        }
        
        public System.Collections.Generic.List<System.Collections.DictionaryEntry> GetCustomersAccessAmountByStore(UtnEmall.Server.EntityModel.StoreEntity store, string session) {
            return base.Channel.GetCustomersAccessAmountByStore(store, session);
        }
        
        public System.Collections.Generic.List<System.Collections.DictionaryEntry> GetCustomersTimeAmount(string session) {
            return base.Channel.GetCustomersTimeAmount(session);
        }
                
        public int GetCustomerFormAccessAmount(UtnEmall.Server.EntityModel.ComponentEntity component, string session) {
            return base.Channel.GetCustomerFormAccessAmount(component, session);
        }
        
        public int GetFormAccessAmount(UtnEmall.Server.EntityModel.ComponentEntity component, string session) {
            return base.Channel.GetFormAccessAmount(component, session);
        }
        
        public System.Collections.Generic.List<System.Collections.DictionaryEntry> GetMenuItemAccessAmounts(UtnEmall.Server.EntityModel.ComponentEntity component, string session) {
            return base.Channel.GetMenuItemAccessAmounts(component, session);
        }
        
        public int GetMenuItemAccessAmount(UtnEmall.Server.EntityModel.ComponentEntity component, string session) {
            return base.Channel.GetMenuItemAccessAmount(component, session);
        }
    }
}
