//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtnEmall.ServerManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UtnEmall.ServerManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add campaign.
        /// </summary>
        internal static string AddCampaign {
            get {
                return ResourceManager.GetString("AddCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add category.
        /// </summary>
        internal static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add customer.
        /// </summary>
        internal static string AddCustomer {
            get {
                return ResourceManager.GetString("AddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group.
        /// </summary>
        internal static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add permission.
        /// </summary>
        internal static string AddPermission {
            get {
                return ResourceManager.GetString("AddPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is empty..
        /// </summary>
        internal static string AddressIsEmpty {
            get {
                return ResourceManager.GetString("AddressIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add service.
        /// </summary>
        internal static string AddService {
            get {
                return ResourceManager.GetString("AddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add store.
        /// </summary>
        internal static string AddStore {
            get {
                return ResourceManager.GetString("AddStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required..
        /// </summary>
        internal static string AllFieldsRequired {
            get {
                return ResourceManager.GetString("AllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Stores.
        /// </summary>
        internal static string AllStores {
            get {
                return ResourceManager.GetString("AllStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service already built..
        /// </summary>
        internal static string AlreadyBuilt {
            get {
                return ResourceManager.GetString("AlreadyBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth day.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigns.
        /// </summary>
        internal static string Campaigns {
            get {
                return ResourceManager.GetString("Campaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty service can&apos;t be built..
        /// </summary>
        internal static string CantBuildEmptyService {
            get {
                return ResourceManager.GetString("CantBuildEmptyService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mall data model couldn&apos;t be deleted..
        /// </summary>
        internal static string CantDeleteMallDataModel {
            get {
                return ResourceManager.GetString("CantDeleteMallDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A category window is already open..
        /// </summary>
        internal static string CategoryWindowStillOpen {
            get {
                return ResourceManager.GetString("CategoryWindowStillOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil state.
        /// </summary>
        internal static string CivilState {
            get {
                return ResourceManager.GetString("CivilState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected item?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected campaign?.
        /// </summary>
        internal static string ConfirmDeleteCampaign {
            get {
                return ResourceManager.GetString("ConfirmDeleteCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected category?.
        /// </summary>
        internal static string ConfirmDeleteCategory {
            get {
                return ResourceManager.GetString("ConfirmDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected customer?.
        /// </summary>
        internal static string ConfirmDeleteCustomer {
            get {
                return ResourceManager.GetString("ConfirmDeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected data model?.
        /// </summary>
        internal static string ConfirmDeleteDataModel {
            get {
                return ResourceManager.GetString("ConfirmDeleteDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected group?.
        /// </summary>
        internal static string ConfirmDeleteGroup {
            get {
                return ResourceManager.GetString("ConfirmDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected service?.
        /// </summary>
        internal static string ConfirmDeleteService {
            get {
                return ResourceManager.GetString("ConfirmDeleteService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected store?.
        /// </summary>
        internal static string ConfirmDeleteStore {
            get {
                return ResourceManager.GetString("ConfirmDeleteStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected user?.
        /// </summary>
        internal static string ConfirmDeleteUser {
            get {
                return ResourceManager.GetString("ConfirmDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error, authentication failed..
        /// </summary>
        internal static string ConnectionErrorAuthenticationFailed {
            get {
                return ResourceManager.GetString("ConnectionErrorAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error, groups couldn&apos;t be loaded..
        /// </summary>
        internal static string ConnectionErrorGroupsNotLoaded {
            get {
                return ResourceManager.GetString("ConnectionErrorGroupsNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error, the item could not be saved..
        /// </summary>
        internal static string ConnectionErrorItemNotSaved {
            get {
                return ResourceManager.GetString("ConnectionErrorItemNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection errors.
        /// </summary>
        internal static string ConnectionErrors {
            get {
                return ResourceManager.GetString("ConnectionErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error, services couldn&apos;t be loaded..
        /// </summary>
        internal static string ConnectionErrorServicesNotLoaded {
            get {
                return ResourceManager.GetString("ConnectionErrorServicesNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error, the item could not be saved..
        /// </summary>
        internal static string ConnectionSaveError {
            get {
                return ResourceManager.GetString("ConnectionSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name.
        /// </summary>
        internal static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name is empty..
        /// </summary>
        internal static string ContactNameIsEmpty {
            get {
                return ResourceManager.GetString("ContactNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerServiceData is null.
        /// </summary>
        internal static string CustomerServiceDataNull {
            get {
                return ResourceManager.GetString("CustomerServiceDataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data model.
        /// </summary>
        internal static string DataModel {
            get {
                return ResourceManager.GetString("DataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed.
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployed.
        /// </summary>
        internal static string Deployed {
            get {
                return ResourceManager.GetString("Deployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is empty..
        /// </summary>
        internal static string DescriptionIsEmpty {
            get {
                return ResourceManager.GetString("DescriptionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A designer is already opened..
        /// </summary>
        internal static string DesignerOpened {
            get {
                return ResourceManager.GetString("DesignerOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit campaign.
        /// </summary>
        internal static string EditCampaign {
            get {
                return ResourceManager.GetString("EditCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        internal static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit customer.
        /// </summary>
        internal static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit group.
        /// </summary>
        internal static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit permission.
        /// </summary>
        internal static string EditPermission {
            get {
                return ResourceManager.GetString("EditPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit service.
        /// </summary>
        internal static string EditService {
            get {
                return ResourceManager.GetString("EditService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit store.
        /// </summary>
        internal static string EditStore {
            get {
                return ResourceManager.GetString("EditStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is empty..
        /// </summary>
        internal static string EmailIsEmpty {
            get {
                return ResourceManager.GetString("EmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty..
        /// </summary>
        internal static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty permissions.
        /// </summary>
        internal static string EmptyPermissions {
            get {
                return ResourceManager.GetString("EmptyPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty text..
        /// </summary>
        internal static string EmptyText {
            get {
                return ResourceManager.GetString("EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is empty..
        /// </summary>
        internal static string EmptyUserName {
            get {
                return ResourceManager.GetString("EmptyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while making the canvas.
        /// </summary>
        internal static string ErrorMakingCanvas {
            get {
                return ResourceManager.GetString("ErrorMakingCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name is duplicated..
        /// </summary>
        internal static string FieldNameDuplicated {
            get {
                return ResourceManager.GetString("FieldNameDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file name is required..
        /// </summary>
        internal static string FieldNameRequired {
            get {
                return ResourceManager.GetString("FieldNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is empty..
        /// </summary>
        internal static string FirstNameIsEmpty {
            get {
                return ResourceManager.GetString("FirstNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group with that name already exists..
        /// </summary>
        internal static string GroupExists {
            get {
                return ResourceManager.GetString("GroupExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide content.
        /// </summary>
        internal static string HideContent {
            get {
                return ResourceManager.GetString("HideContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide preferences.
        /// </summary>
        internal static string HidePreferences {
            get {
                return ResourceManager.GetString("HidePreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of children.
        /// </summary>
        internal static string HowManyChildren {
            get {
                return ResourceManager.GetString("HowManyChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of children can&apos;t be negative..
        /// </summary>
        internal static string HowManyChildrenIsNegative {
            get {
                return ResourceManager.GetString("HowManyChildrenIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers that used it.
        /// </summary>
        internal static string HowManyCustomersUsedForm {
            get {
                return ResourceManager.GetString("HowManyCustomersUsedForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Selected Registers.
        /// </summary>
        internal static string HowManyRegisterSelections {
            get {
                return ResourceManager.GetString("HowManyRegisterSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicks per Menu.
        /// </summary>
        internal static string HowManyTimesMenuWasUsed {
            get {
                return ResourceManager.GetString("HowManyTimesMenuWasUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times it was used.
        /// </summary>
        internal static string HowManyTimesUsedForm {
            get {
                return ResourceManager.GetString("HowManyTimesUsedForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document couldn&apos;t be loaded.
        /// </summary>
        internal static string ImpossibleLoadDocument {
            get {
                return ResourceManager.GetString("ImpossibleLoadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible Save Service.
        /// </summary>
        internal static string ImpossibleSaveService {
            get {
                return ResourceManager.GetString("ImpossibleSaveService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Data Model was built and published successfully..
        /// </summary>
        internal static string InfrastructureServiceBuilt {
            get {
                return ResourceManager.GetString("InfrastructureServiceBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal phone is empty..
        /// </summary>
        internal static string InternalPhoneIsEmpty {
            get {
                return ResourceManager.GetString("InternalPhoneIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service design has an inaccessible form..
        /// </summary>
        internal static string InvalidServicePath {
            get {
                return ResourceManager.GetString("InvalidServicePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is not valid..
        /// </summary>
        internal static string InvalidStartDate {
            get {
                return ResourceManager.GetString("InvalidStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop date is not valid..
        /// </summary>
        internal static string InvalidStopDate {
            get {
                return ResourceManager.GetString("InvalidStopDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Item is already selected..
        /// </summary>
        internal static string ItemAlreadySelected {
            get {
                return ResourceManager.GetString("ItemAlreadySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is empty..
        /// </summary>
        internal static string LastNameIsEmpty {
            get {
                return ResourceManager.GetString("LastNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load campaigns..
        /// </summary>
        internal static string LoadCampaignsFailed {
            get {
                return ResourceManager.GetString("LoadCampaignsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load categories..
        /// </summary>
        internal static string LoadCategoriesFailed {
            get {
                return ResourceManager.GetString("LoadCategoriesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load category list..
        /// </summary>
        internal static string LoadCategoryListFailed {
            get {
                return ResourceManager.GetString("LoadCategoryListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load customers..
        /// </summary>
        internal static string LoadCustomersFailed {
            get {
                return ResourceManager.GetString("LoadCustomersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load data models..
        /// </summary>
        internal static string LoadDataModelFailed {
            get {
                return ResourceManager.GetString("LoadDataModelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some categories have duplicated names, and couldn&apos;t be loaded..
        /// </summary>
        internal static string LoadErrorDuplicatedCategories {
            get {
                return ResourceManager.GetString("LoadErrorDuplicatedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load failed.
        /// </summary>
        internal static string LoadFailed {
            get {
                return ResourceManager.GetString("LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load groups..
        /// </summary>
        internal static string LoadGroupsFailed {
            get {
                return ResourceManager.GetString("LoadGroupsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load service design..
        /// </summary>
        internal static string LoadServiceDesignFailed {
            get {
                return ResourceManager.GetString("LoadServiceDesignFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load services..
        /// </summary>
        internal static string LoadServicesFailed {
            get {
                return ResourceManager.GetString("LoadServicesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while loading statistics..
        /// </summary>
        internal static string LoadStatisticsFailed {
            get {
                return ResourceManager.GetString("LoadStatisticsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stores loaded on the list..
        /// </summary>
        internal static string LoadStoreListFailed {
            get {
                return ResourceManager.GetString("LoadStoreListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load stores..
        /// </summary>
        internal static string LoadStoresFailed {
            get {
                return ResourceManager.GetString("LoadStoresFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load users..
        /// </summary>
        internal static string LoadUsersFailed {
            get {
                return ResourceManager.GetString("LoadUsersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mall.
        /// </summary>
        internal static string Mall {
            get {
                return ResourceManager.GetString("Mall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Form.
        /// </summary>
        internal static string MenuForm {
            get {
                return ResourceManager.GetString("MenuForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is empty..
        /// </summary>
        internal static string NameIsEmpty {
            get {
                return ResourceManager.GetString("NameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New root category.
        /// </summary>
        internal static string NewRootCategory {
            get {
                return ResourceManager.GetString("NewRootCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No campaign was selected..
        /// </summary>
        internal static string NoCampaignSelected {
            get {
                return ResourceManager.GetString("NoCampaignSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A category was not selected..
        /// </summary>
        internal static string NoCategorySelected {
            get {
                return ResourceManager.GetString("NoCategorySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A storage can&apos;t have a connection..
        /// </summary>
        internal static string NoConnectionStorage {
            get {
                return ResourceManager.GetString("NoConnectionStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A customer was not selected..
        /// </summary>
        internal static string NoCustomerSelected {
            get {
                return ResourceManager.GetString("NoCustomerSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last form hasn&apos;t defined a list output..
        /// </summary>
        internal static string NoDataContextDefined {
            get {
                return ResourceManager.GetString("NoDataContextDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; No Data Model Was Loaded &gt;.
        /// </summary>
        internal static string NoDataModelLoaded {
            get {
                return ResourceManager.GetString("NoDataModelLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data model was not selected..
        /// </summary>
        internal static string NoDataModelSelected {
            get {
                return ResourceManager.GetString("NoDataModelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add at least one displayed field..
        /// </summary>
        internal static string NoDisplayedField {
            get {
                return ResourceManager.GetString("NoDisplayedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group was not selected..
        /// </summary>
        internal static string NoGroupSelected {
            get {
                return ResourceManager.GetString("NoGroupSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make an input connection first..
        /// </summary>
        internal static string NoInputConnection {
            get {
                return ResourceManager.GetString("NoInputConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Input Form.
        /// </summary>
        internal static string NoInputForm {
            get {
                return ResourceManager.GetString("NoInputForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item was not selected..
        /// </summary>
        internal static string NoItemSelected {
            get {
                return ResourceManager.GetString("NoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while loading the connections. Note that the statistics will not be affected..
        /// </summary>
        internal static string NonFatalErrorLoadingConnection {
            get {
                return ResourceManager.GetString("NonFatalErrorLoadingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A permission was not selected..
        /// </summary>
        internal static string NoPermissionSelected {
            get {
                return ResourceManager.GetString("NoPermissionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service has not been designed..
        /// </summary>
        internal static string NoServiceDesigned {
            get {
                return ResourceManager.GetString("NoServiceDesigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service was not selected..
        /// </summary>
        internal static string NoServiceSelected {
            get {
                return ResourceManager.GetString("NoServiceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A start form was not selected..
        /// </summary>
        internal static string NoStartForm {
            get {
                return ResourceManager.GetString("NoStartForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No store.
        /// </summary>
        internal static string NoStore {
            get {
                return ResourceManager.GetString("NoStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A store was not selected..
        /// </summary>
        internal static string NoStoreSelected {
            get {
                return ResourceManager.GetString("NoStoreSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No store was loaded on the list..
        /// </summary>
        internal static string NoStoresLoaded {
            get {
                return ResourceManager.GetString("NoStoresLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No title.
        /// </summary>
        internal static string NoTitle {
            get {
                return ResourceManager.GetString("NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        internal static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user was not selected..
        /// </summary>
        internal static string NoUserSelected {
            get {
                return ResourceManager.GetString("NoUserSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output data changed.
        /// </summary>
        internal static string OutputDataContextChanged {
            get {
                return ResourceManager.GetString("OutputDataContextChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner name is empty..
        /// </summary>
        internal static string OwnerNameIsEmpty {
            get {
                return ResourceManager.GetString("OwnerNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirm fields are not equal..
        /// </summary>
        internal static string PasswordAndConfirmNotEqual {
            get {
                return ResourceManager.GetString("PasswordAndConfirmNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty..
        /// </summary>
        internal static string PasswordCantBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A permission already exists for that class.
        /// </summary>
        internal static string PermissionAlreadyExists {
            get {
                return ResourceManager.GetString("PermissionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is empty..
        /// </summary>
        internal static string PhoneIsEmpty {
            get {
                return ResourceManager.GetString("PhoneIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is empty..
        /// </summary>
        internal static string PositionIsEmpty {
            get {
                return ResourceManager.GetString("PositionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to insert sample data inside the data model for testing purposes?.
        /// </summary>
        internal static string QueryInsertTestDataOnInfrastructureService {
            get {
                return ResourceManager.GetString("QueryInsertTestDataOnInfrastructureService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will reset the fields and connections associated to this table. Are you sure you want to proceed?.
        /// </summary>
        internal static string ResetConnectionAndFields {
            get {
                return ResourceManager.GetString("ResetConnectionAndFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will reset the next connections and forms. Are you sure you want to proceed?.
        /// </summary>
        internal static string ResetConnectionAndForm {
            get {
                return ResourceManager.GetString("ResetConnectionAndForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select two different nodes to make a Connection..
        /// </summary>
        internal static string SameNodesSelected {
            get {
                return ResourceManager.GetString("SameNodesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while saving the campaign..
        /// </summary>
        internal static string SaveCampaignError {
            get {
                return ResourceManager.GetString("SaveCampaignError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while saving the category..
        /// </summary>
        internal static string SaveCategoryError {
            get {
                return ResourceManager.GetString("SaveCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while saving the customer..
        /// </summary>
        internal static string SaveCustomerError {
            get {
                return ResourceManager.GetString("SaveCustomerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while saving the data model..
        /// </summary>
        internal static string SaveDataModelError {
            get {
                return ResourceManager.GetString("SaveDataModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while saving..
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while saving the group..
        /// </summary>
        internal static string SaveGroupError {
            get {
                return ResourceManager.GetString("SaveGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while saving the Infrastructure data model..
        /// </summary>
        internal static string SaveInfrastructureError {
            get {
                return ResourceManager.GetString("SaveInfrastructureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while saving the service..
        /// </summary>
        internal static string SaveServiceError {
            get {
                return ResourceManager.GetString("SaveServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while saving the store..
        /// </summary>
        internal static string SaveStoreError {
            get {
                return ResourceManager.GetString("SaveStoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        internal static string SaveSuccessfully {
            get {
                return ResourceManager.GetString("SaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while saving the user..
        /// </summary>
        internal static string SaveUserError {
            get {
                return ResourceManager.GetString("SaveUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the source connection form..
        /// </summary>
        internal static string SelectFormOriginConnection {
            get {
                return ResourceManager.GetString("SelectFormOriginConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the target connection form..
        /// </summary>
        internal static string SelectFormTargetConnection {
            get {
                return ResourceManager.GetString("SelectFormTargetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Point of Origin Connection.
        /// </summary>
        internal static string SelectPointOriginConnection {
            get {
                return ResourceManager.GetString("SelectPointOriginConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the source connection table..
        /// </summary>
        internal static string SelectTableOriginConnection {
            get {
                return ResourceManager.GetString("SelectTableOriginConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the target connection table..
        /// </summary>
        internal static string SelectTableTargetConnection {
            get {
                return ResourceManager.GetString("SelectTableTargetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while building the service..
        /// </summary>
        internal static string ServiceBuildError {
            get {
                return ResourceManager.GetString("ServiceBuildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service was built and published successfully..
        /// </summary>
        internal static string ServiceBuilt {
            get {
                return ResourceManager.GetString("ServiceBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service designer is already opened..
        /// </summary>
        internal static string ServiceDesignerOpened {
            get {
                return ResourceManager.GetString("ServiceDesignerOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service&apos;s design logic is incorrect..
        /// </summary>
        internal static string ServiceDesignLogicIncorrect {
            get {
                return ResourceManager.GetString("ServiceDesignLogicIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service was saved successfully..
        /// </summary>
        internal static string ServiceSavedSuccessfully {
            get {
                return ResourceManager.GetString("ServiceSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service statistic viewer is already opened..
        /// </summary>
        internal static string ServiceStatisticsViewerOpened {
            get {
                return ResourceManager.GetString("ServiceStatisticsViewerOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show content.
        /// </summary>
        internal static string ShowContent {
            get {
                return ResourceManager.GetString("ShowContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Data.
        /// </summary>
        internal static string ShowData {
            get {
                return ResourceManager.GetString("ShowData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show preferences.
        /// </summary>
        internal static string ShowPreferences {
            get {
                return ResourceManager.GetString("ShowPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date can&apos;t be in the past..
        /// </summary>
        internal static string StartDateInThePast {
            get {
                return ResourceManager.GetString("StartDateInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Date.
        /// </summary>
        internal static string StopDate {
            get {
                return ResourceManager.GetString("StopDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stop date can&apos;t be in the past..
        /// </summary>
        internal static string StopDateInThePast {
            get {
                return ResourceManager.GetString("StopDateInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stop date can&apos;t be before the start date..
        /// </summary>
        internal static string StopDateSmallerStart {
            get {
                return ResourceManager.GetString("StopDateSmallerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store number.
        /// </summary>
        internal static string StoreNumber {
            get {
                return ResourceManager.GetString("StoreNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store number is empty..
        /// </summary>
        internal static string StoreNumberIsEmpty {
            get {
                return ResourceManager.GetString("StoreNumberIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store number is not a valid number..
        /// </summary>
        internal static string StoreNumberNotValid {
            get {
                return ResourceManager.GetString("StoreNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        internal static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A table with the given name already exists..
        /// </summary>
        internal static string TableNameDupplicated {
            get {
                return ResourceManager.GetString("TableNameDupplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Name is empty..
        /// </summary>
        internal static string TableNameRequired {
            get {
                return ResourceManager.GetString("TableNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Error.
        /// </summary>
        internal static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is empty..
        /// </summary>
        internal static string UserNameIsEmpty {
            get {
                return ResourceManager.GetString("UserNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website is empty..
        /// </summary>
        internal static string WebsiteIsEmpty {
            get {
                return ResourceManager.GetString("WebsiteIsEmpty", resourceCulture);
            }
        }
    }
}
