//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.ServiceBuilder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBuilder.IServiceBuilder")]
    public interface IServiceBuilder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBuilder/BuildAndImplementInfrastructureService", ReplyAction="http://tempuri.org/IServiceBuilder/BuildAndImplementInfrastructureServiceResponse" +
            "")]
        [UtnEmall.Server.Core.ReferencePreservingDataContractFormat]
        bool BuildAndImplementInfrastructureService(UtnEmall.Server.EntityModel.DataModelEntity serviceDataModel, bool insertTestData, string sessionIdentifier);

        [UtnEmall.Server.Core.ReferencePreservingDataContractFormat]
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceBuilder/BuildAndImplementCustomService", ReplyAction = "http://tempuri.org/IServiceBuilder/BuildAndImplementCustomServiceResponse")]
        bool BuildAndImplementCustomService(UtnEmall.Server.EntityModel.CustomerServiceDataEntity customerService, string sessionIdentifier);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IServiceBuilderChannel : WebApplication.ServiceBuilder.IServiceBuilder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceBuilderClient : System.ServiceModel.ClientBase<WebApplication.ServiceBuilder.IServiceBuilder>, WebApplication.ServiceBuilder.IServiceBuilder {
        
        public ServiceBuilderClient() {
        }
        
        public ServiceBuilderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBuilderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBuilderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBuilderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool BuildAndImplementInfrastructureService(UtnEmall.Server.EntityModel.DataModelEntity serviceDataModel, bool insertTestData, string sessionIdentifier) {
            return base.Channel.BuildAndImplementInfrastructureService(serviceDataModel, insertTestData, sessionIdentifier);
        }
        
        public bool BuildAndImplementCustomService(UtnEmall.Server.EntityModel.CustomerServiceDataEntity customerService, string sessionIdentifier) {
            return base.Channel.BuildAndImplementCustomService(customerService, sessionIdentifier);
        }
    }
}
