//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.ServiceReferenceCustomer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCustomer.ICustomer")]
    public interface ICustomer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/Save", ReplyAction="http://tempuri.org/ICustomer/SaveResponse")]
        UtnEmall.Server.EntityModel.CustomerEntity Save(UtnEmall.Server.EntityModel.CustomerEntity customerEntity, string session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/Delete", ReplyAction="http://tempuri.org/ICustomer/DeleteResponse")]
        UtnEmall.Server.EntityModel.CustomerEntity Delete(UtnEmall.Server.EntityModel.CustomerEntity customerEntity, string session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/GetCustomer", ReplyAction="http://tempuri.org/ICustomer/GetCustomerResponse")]
        UtnEmall.Server.EntityModel.CustomerEntity GetCustomer(int id, bool loadRelation, string session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/GetAllCustomer", ReplyAction="http://tempuri.org/ICustomer/GetAllCustomerResponse")]
        System.Collections.Generic.List<UtnEmall.Server.EntityModel.CustomerEntity> GetAllCustomer(bool loadRelation, string session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/GetCustomerWhere", ReplyAction="http://tempuri.org/ICustomer/GetCustomerWhereResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.Base.OperatorType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.CustomerEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.Error>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.Error))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.PreferenceEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.PreferenceEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.CategoryEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.CategoryEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.ServiceCategoryEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.ServiceCategoryEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.ServiceEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.MallEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.ServiceEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.StoreEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.StoreEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.StoreCategoryEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.StoreCategoryEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.DataModelEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.DataModelEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.TableEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.TableEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.FieldEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.FieldEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.ComponentEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.CustomerServiceDataEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.ComponentEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.ConnectionWidgetEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.ConnectionWidgetEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.ConnectionPointEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.RelationEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.RelationEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.UserEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.UserEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.UserGroupEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.UserGroupEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.GroupEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.PermissionEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.PermissionEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.CustomerEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.DeviceProfileEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.DeviceProfileEntity))]
        System.Collections.Generic.List<UtnEmall.Server.EntityModel.CustomerEntity> GetCustomerWhere(string propertyName, object expValue, bool loadRelation, UtnEmall.Server.Base.OperatorType operatorType, string session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/GetCustomerWhereEqual", ReplyAction="http://tempuri.org/ICustomer/GetCustomerWhereEqualResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.Base.OperatorType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.CustomerEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.Error>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.Error))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.PreferenceEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.PreferenceEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.CategoryEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.CategoryEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.ServiceCategoryEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.ServiceCategoryEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.ServiceEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.MallEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.ServiceEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.StoreEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.StoreEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.StoreCategoryEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.StoreCategoryEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.DataModelEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.DataModelEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.TableEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.TableEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.FieldEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.FieldEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.ComponentEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.CustomerServiceDataEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.ComponentEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.ConnectionWidgetEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.ConnectionWidgetEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.ConnectionPointEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.RelationEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.RelationEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.UserEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.UserEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.UserGroupEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.UserGroupEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.GroupEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.PermissionEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.PermissionEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.CustomerEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<UtnEmall.Server.EntityModel.DeviceProfileEntity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UtnEmall.Server.EntityModel.DeviceProfileEntity))]
        System.Collections.Generic.List<UtnEmall.Server.EntityModel.CustomerEntity> GetCustomerWhereEqual(string propertyName, object expValue, bool loadRelation, string session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/Validate", ReplyAction="http://tempuri.org/ICustomer/ValidateResponse")]
        bool Validate(UtnEmall.Server.EntityModel.CustomerEntity customer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICustomerChannel : WebApplication.ServiceReferenceCustomer.ICustomer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CustomerClient : System.ServiceModel.ClientBase<WebApplication.ServiceReferenceCustomer.ICustomer>, WebApplication.ServiceReferenceCustomer.ICustomer {
        
        public CustomerClient() {
        }
        
        public CustomerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UtnEmall.Server.EntityModel.CustomerEntity Save(UtnEmall.Server.EntityModel.CustomerEntity customerEntity, string session) {
            return base.Channel.Save(customerEntity, session);
        }
        
        public UtnEmall.Server.EntityModel.CustomerEntity Delete(UtnEmall.Server.EntityModel.CustomerEntity customerEntity, string session) {
            return base.Channel.Delete(customerEntity, session);
        }
        
        public UtnEmall.Server.EntityModel.CustomerEntity GetCustomer(int id, bool loadRelation, string session) {
            return base.Channel.GetCustomer(id, loadRelation, session);
        }
        
        public System.Collections.Generic.List<UtnEmall.Server.EntityModel.CustomerEntity> GetAllCustomer(bool loadRelation, string session) {
            return base.Channel.GetAllCustomer(loadRelation, session);
        }
        
        public System.Collections.Generic.List<UtnEmall.Server.EntityModel.CustomerEntity> GetCustomerWhere(string propertyName, object expValue, bool loadRelation, UtnEmall.Server.Base.OperatorType operatorType, string session) {
            return base.Channel.GetCustomerWhere(propertyName, expValue, loadRelation, operatorType, session);
        }
        
        public System.Collections.Generic.List<UtnEmall.Server.EntityModel.CustomerEntity> GetCustomerWhereEqual(string propertyName, object expValue, bool loadRelation, string session) {
            return base.Channel.GetCustomerWhereEqual(propertyName, expValue, loadRelation, session);
        }
        
        public bool Validate(UtnEmall.Server.EntityModel.CustomerEntity customer) {
            return base.Channel.Validate(customer);
        }
    }
}
