//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.1433
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using UtnEmall.Client.EntityModel;
using Microsoft.Tools.ServiceModel;
using System.Collections.ObjectModel;

namespace UtnEmall.Client.ServiceAccessLayer
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IStatisticsDataRecollection
    {

        bool AddStatisticsData(Collection<UserActionClientDataEntity> statisticsDataList, string sessionId);
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "AddStatisticsData", Namespace = "http://tempuri.org/")]
    public partial class AddStatisticsDataRequest
    {

        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.datacontract.org/2004/07/UtnEmall.Server.EntityModel")]
        public Collection<UserActionClientDataEntity> statisticsDataList;

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Namespace = "http://tempuri.org/", Order = 1)]
        public string sessionId;

        public AddStatisticsDataRequest()
        {
        }

        public AddStatisticsDataRequest(Collection<UserActionClientDataEntity> statisticsDataList, string sessionId)
        {
            this.statisticsDataList = statisticsDataList;
            this.sessionId = sessionId;
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "AddStatisticsDataResponse", Namespace = "http://tempuri.org/")]
    public partial class AddStatisticsDataResponse
    {

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public bool AddStatisticsDataResult;

        public AddStatisticsDataResponse()
        {
        }

        public AddStatisticsDataResponse(bool AddStatisticsDataResult)
        {
            this.AddStatisticsDataResult = AddStatisticsDataResult;
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class StatisticsDataRecollectionClient : Microsoft.Tools.ServiceModel.CFClientBase<IStatisticsDataRecollection>, IStatisticsDataRecollection
    {

        public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://UtnEmallserver/IStatisticsDataRecollection");

        public StatisticsDataRecollectionClient() :
            this(CreateDefaultBinding(), EndpointAddress)
        {
        }

        public StatisticsDataRecollectionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
            addProtectionRequirements(binding);
        }

        private AddStatisticsDataResponse AddStatisticsData(AddStatisticsDataRequest request)
        {
            CFInvokeInfo info = new CFInvokeInfo();
            info.Action = "http://tempuri.org/IStatisticsDataRecollection/AddStatisticsData";
            info.RequestIsWrapped = true;
            info.ReplyAction = "http://tempuri.org/IStatisticsDataRecollection/AddStatisticsDataResponse";
            info.ResponseIsWrapped = true;
            AddStatisticsDataResponse retVal = base.Invoke<AddStatisticsDataRequest, AddStatisticsDataResponse>(info, request);
            return retVal;
        }

        public bool AddStatisticsData(Collection<UserActionClientDataEntity> statisticsDataList, string sessionId)
        {
            AddStatisticsDataRequest request = new AddStatisticsDataRequest(statisticsDataList, sessionId);
            AddStatisticsDataResponse response = this.AddStatisticsData(request);
            return response.AddStatisticsDataResult;
        }

        public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
        {
            System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
            binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
            binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
            return binding;
        }

        private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
        {
            if ((IsSecureMessageBinding(binding) == false))
            {
                return;
            }
            System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
            ApplyProtection("http://tempuri.org/IStatisticsDataRecollection/AddStatisticsData", cpr.IncomingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IStatisticsDataRecollection/AddStatisticsData", cpr.IncomingEncryptionParts, true);
            if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
            {
                ApplyProtection("*", cpr.OutgoingSignatureParts, true);
                ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
            }
            else
            {
                ApplyProtection("http://tempuri.org/IStatisticsDataRecollection/AddStatisticsDataResponse", cpr.OutgoingSignatureParts, true);
                ApplyProtection("http://tempuri.org/IStatisticsDataRecollection/AddStatisticsDataResponse", cpr.OutgoingEncryptionParts, true);
            }
            this.Parameters.Add(cpr);
        }
    }
}