//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.1433
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------


using Microsoft.Tools.ServiceModel;
namespace UtnEmall.Client.ServiceAccessLayer
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IFileTransferService
    {

        RemoteFileInfo DownloadFile(DownloadRequest request1, string sessionIdentifier);
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/UtnEmall.Server.Core")]
    public partial class DownloadRequest
    {

        private string fileNameField;

        private string fileDateTimeField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string FileDateTime
        {
            get
            {
                return this.fileDateTimeField;
            }
            set
            {
                this.fileDateTimeField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
    [System.SerializableAttribute()]
    
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/UtnEmall.Server.Core")]
    public partial class RemoteFileInfo
    {

        private string fileNameField;

        private long lengthField;

        private bool lengthFieldSpecified;

        private byte[] fileByteStreamField;

        private bool notChangedField;

        private bool notChangedFieldSpecified;

        private string fileDateTimeField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public long Length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LengthSpecified
        {
            get
            {
                return this.lengthFieldSpecified;
            }
            set
            {
                this.lengthFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", IsNullable = true, Order = 2)]
        public byte[] FileByteStream
        {
            get
            {
                return this.fileByteStreamField;
            }
            set
            {
                this.fileByteStreamField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public bool NotChanged
        {
            get
            {
                return this.notChangedField;
            }
            set
            {
                this.notChangedField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotChangedSpecified
        {
            get
            {
                return this.notChangedFieldSpecified;
            }
            set
            {
                this.notChangedFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public string FileDateTime
        {
            get
            {
                return this.fileDateTimeField;
            }
            set
            {
                this.fileDateTimeField = value;
            }
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "DownloadFile", Namespace = "http://tempuri.org/")]
    public partial class DownloadFileRequest
    {

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Namespace = "http://tempuri.org/", Order = 0)]
        public DownloadRequest request;

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Namespace = "http://tempuri.org/", Order = 1)]
        public string sessionIdentifier;

        public DownloadFileRequest()
        {
        }

        public DownloadFileRequest(DownloadRequest request, string sessionIdentifier)
        {
            this.request = request;
            this.sessionIdentifier = sessionIdentifier;
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "DownloadFileResponse", Namespace = "http://tempuri.org/")]
    public partial class DownloadFileResponse
    {

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Namespace = "http://tempuri.org/", Order = 0)]
        public RemoteFileInfo DownloadFileResult;

        public DownloadFileResponse()
        {
        }

        public DownloadFileResponse(RemoteFileInfo DownloadFileResult)
        {
            this.DownloadFileResult = DownloadFileResult;
        }
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class FileTransferServiceClient : Microsoft.Tools.ServiceModel.CFClientBase<IFileTransferService>, IFileTransferService
    {

        public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://cpu20:8081/FileTransferService");

        public FileTransferServiceClient() :
            this(CreateDefaultBinding(), EndpointAddress)
        {
        }

        public FileTransferServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
            addProtectionRequirements(binding);
        }

        private DownloadFileResponse DownloadFile(DownloadFileRequest request)
        {
            CFInvokeInfo info = new CFInvokeInfo();
            info.Action = "http://tempuri.org/IFileTransferService/DownloadFile";
            info.RequestIsWrapped = true;
            info.ReplyAction = "http://tempuri.org/IFileTransferService/DownloadFileResponse";
            info.ResponseIsWrapped = true;
            DownloadFileResponse retVal = base.Invoke<DownloadFileRequest, DownloadFileResponse>(info, request);
            return retVal;
        }

        public RemoteFileInfo DownloadFile(DownloadRequest request1, string sessionIdentifier)
        {
            DownloadFileRequest request = new DownloadFileRequest(request1, sessionIdentifier);
            DownloadFileResponse response = this.DownloadFile(request);
            return response.DownloadFileResult;
        }

        public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
        {
            System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
            binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
            binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
            return binding;
        }

        private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
        {
            if ((IsSecureMessageBinding(binding) == false))
            {
                return;
            }
            System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
            ApplyProtection("http://tempuri.org/IFileTransferService/DownloadFile", cpr.IncomingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IFileTransferService/DownloadFile", cpr.IncomingEncryptionParts, true);
            if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
            {
                ApplyProtection("*", cpr.OutgoingSignatureParts, true);
                ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
            }
            else
            {
                ApplyProtection("http://tempuri.org/IFileTransferService/DownloadFileResponse", cpr.OutgoingSignatureParts, true);
                ApplyProtection("http://tempuri.org/IFileTransferService/DownloadFileResponse", cpr.OutgoingEncryptionParts, true);
            }
            this.Parameters.Add(cpr);
        }
    }
}