//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilverlightVisualDesigners.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilverlightVisualDesigners.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer service was saved successfully..
        /// </summary>
        public static string CustomerServiceSuccessfullySaved {
            get {
                return ResourceManager.GetString("CustomerServiceSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data model was saved successfully..
        /// </summary>
        public static string DataModelSuccessfullySaved {
            get {
                return ResourceManager.GetString("DataModelSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string EnterSingleDataDescriptionEmpty {
            get {
                return ResourceManager.GetString("EnterSingleDataDescriptionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string EnterSingleDataFormName {
            get {
                return ResourceManager.GetString("EnterSingleDataFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string EnterSingleDataNameEmpty {
            get {
                return ResourceManager.GetString("EnterSingleDataNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is required..
        /// </summary>
        public static string EnterSingleDataTypeEmpty {
            get {
                return ResourceManager.GetString("EnterSingleDataTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while saving the customer service..
        /// </summary>
        public static string ErrorWhileSavingCustomerService {
            get {
                return ResourceManager.GetString("ErrorWhileSavingCustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while saving the data model..
        /// </summary>
        public static string ErrorWhileSavingDataModel {
            get {
                return ResourceManager.GetString("ErrorWhileSavingDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated field name.
        /// </summary>
        public static string FieldSameNameError {
            get {
                return ResourceManager.GetString("FieldSameNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A field with the same name already exists..
        /// </summary>
        public static string FieldSameNameMessage {
            get {
                return ResourceManager.GetString("FieldSameNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not possible to set a menu as source connection. Must select a menu item as source connection on a menu form..
        /// </summary>
        public static string InvalidConnection_MenuItemMustBeSourceInMenu {
            get {
                return ResourceManager.GetString("InvalidConnection_MenuItemMustBeSourceInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Connection.
        /// </summary>
        public static string InvalidConnectionError {
            get {
                return ResourceManager.GetString("InvalidConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need a valid input information to connect this widget, please check the connection source widget..
        /// </summary>
        public static string InvalidConnectionMessage {
            get {
                return ResourceManager.GetString("InvalidConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid custom service.
        /// </summary>
        public static string InvalidCustomService {
            get {
                return ResourceManager.GetString("InvalidCustomService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field name.
        /// </summary>
        public static string InvalidFieldNameError {
            get {
                return ResourceManager.GetString("InvalidFieldNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name is required..
        /// </summary>
        public static string InvalidFieldNameMessage {
            get {
                return ResourceManager.GetString("InvalidFieldNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service design has an inaccessible form..
        /// </summary>
        public static string InvalidServicePath {
            get {
                return ResourceManager.GetString("InvalidServicePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid table name.
        /// </summary>
        public static string InvalidTableNameError {
            get {
                return ResourceManager.GetString("InvalidTableNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name is required..
        /// </summary>
        public static string InvalidTableNameMessage {
            get {
                return ResourceManager.GetString("InvalidTableNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type of widget.
        /// </summary>
        public static string InvalidTypeOfWidget {
            get {
                return ResourceManager.GetString("InvalidTypeOfWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string ListFormName {
            get {
                return ResourceManager.GetString("ListFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuFormName {
            get {
                return ResourceManager.GetString("MenuFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add at least one displayed field..
        /// </summary>
        public static string NoListItems {
            get {
                return ResourceManager.GetString("NoListItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add at least one menu option..
        /// </summary>
        public static string NoMenuItems {
            get {
                return ResourceManager.GetString("NoMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a data type..
        /// </summary>
        public static string NoSelectedDataType {
            get {
                return ResourceManager.GetString("NoSelectedDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a start form..
        /// </summary>
        public static string NoStartForm {
            get {
                return ResourceManager.GetString("NoStartForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving.
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while saving..
        /// </summary>
        public static string SaveErrorMessage {
            get {
                return ResourceManager.GetString("SaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Data.
        /// </summary>
        public static string ShowDataFormName {
            get {
                return ResourceManager.GetString("ShowDataFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated table name.
        /// </summary>
        public static string TableNameDuplicateError {
            get {
                return ResourceManager.GetString("TableNameDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A table with the same name already exists..
        /// </summary>
        public static string TableNameDuplicateMessage {
            get {
                return ResourceManager.GetString("TableNameDuplicateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No Name&gt;.
        /// </summary>
        public static string TableNoName {
            get {
                return ResourceManager.GetString("TableNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table has relations. Can´t be set as storage..
        /// </summary>
        public static string TheTableHasRelations {
            get {
                return ResourceManager.GetString("TheTableHasRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string TitleFormEmpty {
            get {
                return ResourceManager.GetString("TitleFormEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnhandledError.
        /// </summary>
        public static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
    }
}
